optimizer:
  name: adam
  lr: 0.001 # not 1e-3
  weight_decay: 0

train:
  epoch: 1000
  batch_size: 4096
  save_model: false
  loss: pairwise # bpr
  log_loss: false # whether to log loss
  test_step: 3 # evaluate per {test_step} epochs
  patience: 5
  reproducible: true
  seed: 2023
  #pretrain_path: ./checkpoint/xxxx.pth

test:
  metrics: [recall, ndcg] # choose in {ndcg, recall, precision, mrr}
  k: [10, 20, 40] # top-k
  batch_size: 1024 # How many users per batch during validation

data:
  type: general_cf # choose in {general_cf, multi_behavior, sequential, social}
  name: gowalla


model:
  name: lightgcn # case-insensitive
  keep_rate: 0.5
  layer_num: 3
  reg_weight: 1e-4
  embedding_size: 64

tune:
  enable: True # Whether to enable grid search to search for optimal hyperparameters
  hyperparameters: [keep_rate] # The name of the hyperparameter
  keep_rate: [0.25, 0.5, 1.0]
